/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : Id,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'specialty' : string,
  'message' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface Combo {
  'id' : Id,
  'validity' : string,
  'regularPriceCLP' : bigint,
  'agendaproUrl' : string,
  'name' : string,
  'description' : string,
  'comboType' : ComboType,
  'cuposTotal' : bigint,
  'servicesIncluded' : Array<Id>,
  'priceCLP' : bigint,
}
export type ComboType = { 'untilDecember' : null } |
  { 'monthly' : null } |
  { 'newClient' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Error_ = { 'invalidInput' : string } |
  { 'notFound' : string } |
  { 'unauthorized' : string };
export type Id = bigint;
export type MintableItemType = { 'service' : null } |
  { 'combo' : null };
export interface MintedServiceToken {
  'itemId' : bigint,
  'tokenId' : bigint,
  'mintedAt' : bigint,
  'itemName' : string,
  'itemType' : MintableItemType,
  'priceVusd' : bigint,
  'walletId' : WalletId,
}
export interface Partner {
  'id' : Id,
  'name' : string,
  'description' : string,
  'logoText' : string,
}
export interface Product {
  'id' : Id,
  'name' : string,
  'description' : string,
  'usage' : string,
  'badge' : [] | [ProductBadge],
}
export type ProductBadge = { 'new' : null } |
  { 'recommended' : null };
export type Result = { 'ok' : Application } |
  { 'err' : Error_ };
export type Result_1 = { 'ok' : VusdMintResult } |
  { 'err' : Error_ };
export type Result_2 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface Service {
  'id' : Id,
  'durationMins' : bigint,
  'agendaproUrl' : string,
  'techniques' : Array<string>,
  'toolsIncluded' : Array<string>,
  'allIncluded' : boolean,
  'name' : string,
  'description' : string,
  'cuposTotal' : bigint,
  'category' : ServiceCategory,
  'priceCLP' : bigint,
  'longDescription' : string,
}
export type ServiceCategory = { 'especial' : null } |
  { 'corporal' : null } |
  { 'facial' : null };
export interface Testimonial {
  'id' : Id,
  'clientName' : string,
  'comment' : string,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface VusdDemoConfig {
  'demoTopupAmount' : bigint,
  'clpUsdRate' : bigint,
}
export interface VusdMintResult {
  'tokenId' : bigint,
  'newBalance' : bigint,
  'walletId' : WalletId,
}
export interface VusdWallet {
  'balance' : bigint,
  'createdAt' : bigint,
  'walletId' : WalletId,
}
export type WalletId = string;
export interface Worker {
  'id' : Id,
  'bio' : string,
  'servicesIds' : Array<Id>,
  'name' : string,
  'role' : string,
  'silhouetteVariant' : bigint,
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_2>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'connectDemoWallet' : ActorMethod<[], VusdWallet>,
  'execute' : ActorMethod<[string], Result__1>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCombos' : ActorMethod<[], Array<Combo>>,
  'getMintedTokens' : ActorMethod<[WalletId], Array<MintedServiceToken>>,
  'getPartners' : ActorMethod<[], Array<Partner>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getServicesByCategory' : ActorMethod<[ServiceCategory], Array<Service>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getVusdConfig' : ActorMethod<[], VusdDemoConfig>,
  'getVusdWallet' : ActorMethod<[WalletId], [] | [VusdWallet]>,
  'getWorkers' : ActorMethod<[], Array<Worker>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'mintServiceToken' : ActorMethod<
    [WalletId, MintableItemType, bigint, string, bigint],
    Result_1
  >,
  'schema' : ActorMethod<[], string>,
  'submitApplication' : ActorMethod<[string, string, string, string], Result>,
  'topupVusd' : ActorMethod<[WalletId], VusdWallet>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];