/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WalletId = IDL.Text;
export const VusdWallet = IDL.Record({
  'balance' : IDL.Nat,
  'createdAt' : IDL.Nat,
  'walletId' : WalletId,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Id = IDL.Nat;
export const ComboType = IDL.Variant({
  'untilDecember' : IDL.Null,
  'monthly' : IDL.Null,
  'newClient' : IDL.Null,
});
export const Combo = IDL.Record({
  'id' : Id,
  'validity' : IDL.Text,
  'regularPriceCLP' : IDL.Nat,
  'agendaproUrl' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'comboType' : ComboType,
  'cuposTotal' : IDL.Nat,
  'servicesIncluded' : IDL.Vec(Id),
  'priceCLP' : IDL.Nat,
});
export const MintableItemType = IDL.Variant({
  'service' : IDL.Null,
  'combo' : IDL.Null,
});
export const MintedServiceToken = IDL.Record({
  'itemId' : IDL.Nat,
  'tokenId' : IDL.Nat,
  'mintedAt' : IDL.Nat,
  'itemName' : IDL.Text,
  'itemType' : MintableItemType,
  'priceVusd' : IDL.Nat,
  'walletId' : WalletId,
});
export const Partner = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'logoText' : IDL.Text,
});
export const ProductBadge = IDL.Variant({
  'new' : IDL.Null,
  'recommended' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'usage' : IDL.Text,
  'badge' : IDL.Opt(ProductBadge),
});
export const ServiceCategory = IDL.Variant({
  'especial' : IDL.Null,
  'corporal' : IDL.Null,
  'facial' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : Id,
  'durationMins' : IDL.Nat,
  'agendaproUrl' : IDL.Text,
  'techniques' : IDL.Vec(IDL.Text),
  'toolsIncluded' : IDL.Vec(IDL.Text),
  'allIncluded' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'cuposTotal' : IDL.Nat,
  'category' : ServiceCategory,
  'priceCLP' : IDL.Nat,
  'longDescription' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : Id,
  'clientName' : IDL.Text,
  'comment' : IDL.Text,
});
export const VusdDemoConfig = IDL.Record({
  'demoTopupAmount' : IDL.Nat,
  'clpUsdRate' : IDL.Nat,
});
export const Worker = IDL.Record({
  'id' : Id,
  'bio' : IDL.Text,
  'servicesIds' : IDL.Vec(Id),
  'name' : IDL.Text,
  'role' : IDL.Text,
  'silhouetteVariant' : IDL.Nat,
});
export const VusdMintResult = IDL.Record({
  'tokenId' : IDL.Nat,
  'newBalance' : IDL.Nat,
  'walletId' : WalletId,
});
export const Error_ = IDL.Variant({
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Text,
  'unauthorized' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : VusdMintResult, 'err' : Error_ });
export const Timestamp = IDL.Nat;
export const Application = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'specialty' : IDL.Text,
  'message' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : Application, 'err' : Error_ });

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'connectDemoWallet' : IDL.Func([], [VusdWallet], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCombos' : IDL.Func([], [IDL.Vec(Combo)], ['query']),
  'getMintedTokens' : IDL.Func(
      [WalletId],
      [IDL.Vec(MintedServiceToken)],
      ['query'],
    ),
  'getPartners' : IDL.Func([], [IDL.Vec(Partner)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getServicesByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(Service)],
      ['query'],
    ),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getVusdConfig' : IDL.Func([], [VusdDemoConfig], ['query']),
  'getVusdWallet' : IDL.Func([WalletId], [IDL.Opt(VusdWallet)], ['query']),
  'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'mintServiceToken' : IDL.Func(
      [WalletId, MintableItemType, IDL.Nat, IDL.Text, IDL.Nat],
      [Result_1],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'topupVusd' : IDL.Func([WalletId], [VusdWallet], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WalletId = IDL.Text;
  const VusdWallet = IDL.Record({
    'balance' : IDL.Nat,
    'createdAt' : IDL.Nat,
    'walletId' : WalletId,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Id = IDL.Nat;
  const ComboType = IDL.Variant({
    'untilDecember' : IDL.Null,
    'monthly' : IDL.Null,
    'newClient' : IDL.Null,
  });
  const Combo = IDL.Record({
    'id' : Id,
    'validity' : IDL.Text,
    'regularPriceCLP' : IDL.Nat,
    'agendaproUrl' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'comboType' : ComboType,
    'cuposTotal' : IDL.Nat,
    'servicesIncluded' : IDL.Vec(Id),
    'priceCLP' : IDL.Nat,
  });
  const MintableItemType = IDL.Variant({
    'service' : IDL.Null,
    'combo' : IDL.Null,
  });
  const MintedServiceToken = IDL.Record({
    'itemId' : IDL.Nat,
    'tokenId' : IDL.Nat,
    'mintedAt' : IDL.Nat,
    'itemName' : IDL.Text,
    'itemType' : MintableItemType,
    'priceVusd' : IDL.Nat,
    'walletId' : WalletId,
  });
  const Partner = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'logoText' : IDL.Text,
  });
  const ProductBadge = IDL.Variant({
    'new' : IDL.Null,
    'recommended' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'usage' : IDL.Text,
    'badge' : IDL.Opt(ProductBadge),
  });
  const ServiceCategory = IDL.Variant({
    'especial' : IDL.Null,
    'corporal' : IDL.Null,
    'facial' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : Id,
    'durationMins' : IDL.Nat,
    'agendaproUrl' : IDL.Text,
    'techniques' : IDL.Vec(IDL.Text),
    'toolsIncluded' : IDL.Vec(IDL.Text),
    'allIncluded' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'cuposTotal' : IDL.Nat,
    'category' : ServiceCategory,
    'priceCLP' : IDL.Nat,
    'longDescription' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : Id,
    'clientName' : IDL.Text,
    'comment' : IDL.Text,
  });
  const VusdDemoConfig = IDL.Record({
    'demoTopupAmount' : IDL.Nat,
    'clpUsdRate' : IDL.Nat,
  });
  const Worker = IDL.Record({
    'id' : Id,
    'bio' : IDL.Text,
    'servicesIds' : IDL.Vec(Id),
    'name' : IDL.Text,
    'role' : IDL.Text,
    'silhouetteVariant' : IDL.Nat,
  });
  const VusdMintResult = IDL.Record({
    'tokenId' : IDL.Nat,
    'newBalance' : IDL.Nat,
    'walletId' : WalletId,
  });
  const Error_ = IDL.Variant({
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Text,
    'unauthorized' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : VusdMintResult, 'err' : Error_ });
  const Timestamp = IDL.Nat;
  const Application = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'specialty' : IDL.Text,
    'message' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : Application, 'err' : Error_ });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'connectDemoWallet' : IDL.Func([], [VusdWallet], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCombos' : IDL.Func([], [IDL.Vec(Combo)], ['query']),
    'getMintedTokens' : IDL.Func(
        [WalletId],
        [IDL.Vec(MintedServiceToken)],
        ['query'],
      ),
    'getPartners' : IDL.Func([], [IDL.Vec(Partner)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getServicesByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getVusdConfig' : IDL.Func([], [VusdDemoConfig], ['query']),
    'getVusdWallet' : IDL.Func([WalletId], [IDL.Opt(VusdWallet)], ['query']),
    'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'mintServiceToken' : IDL.Func(
        [WalletId, MintableItemType, IDL.Nat, IDL.Text, IDL.Nat],
        [Result_1],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'topupVusd' : IDL.Func([WalletId], [VusdWallet], []),
  });
};

export const init = ({ IDL }) => { return []; };